stages:
  - setup

download_plugins:
  stage: setup
  image: alpine:latest
  script:
    - apk add --no-cache curl unzip
    - curl -o wordpress.zip https://wordpress.org/latest.zip
    - unzip wordpress.zip
    - cp -r wordpress/* .               # Copy files/folders to current dir
    - cp -r wordpress/.* . || true      # Copy hidden files (optional)
    - rm -rf wordpress wordpress.zip

    # Create plugin folder if it doesn't exist
    - mkdir -p wp-content/plugins

    # Download Contact Form 7 plugin
    - curl -L -o wp-content/plugins/contact-form-7.zip https://downloads.wordpress.org/plugin/contact-form-7.latest-stable.zip
    - unzip wp-content/plugins/contact-form-7.zip -d wp-content/plugins/
    - rm wp-content/plugins/contact-form-7.zip

    # Download GTM plugin
    - curl -L -o wp-content/plugins/gtm.zip https://downloads.wordpress.org/plugin/duracelltomi-google-tag-manager.latest-stable.zip
    - unzip wp-content/plugins/gtm.zip -d wp-content/plugins/
    - rm wp-content/plugins/gtm.zip

  artifacts:
    paths:
      - wp-admin/
      - wp-includes/
      - wp-content/plugins/
      - index.php
      - wp-config-sample.php
      - readme.html
      - license.txt
